[build]
target = "frontend/index.html"
dist = "target/dist"
release = false

[[hooks]]
stage = "build"
command = "sh"
command_arguments = [
  "-c",
  "npx tailwindcss -i frontend/input.css -o frontend/assets/tailwind.css -m -c frontend/tailwind.config.js"
]
